/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";

export const InstallationModel: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "InstallationModel",
    modelProperties: {
      installationId: {
        serializedName: "installationId",
        required: true,
        type: {
          name: "String"
        }
      },
      userId: {
        serializedName: "userId",
        type: {
          name: "String"
        }
      },
      lastActiveOn: {
        serializedName: "lastActiveOn",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      lastUpdate: {
        serializedName: "lastUpdate",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      platform: {
        serializedName: "platform",
        required: true,
        type: {
          name: "String"
        }
      },
      pushChannel: {
        serializedName: "pushChannel",
        required: true,
        type: {
          name: "String"
        }
      },
      expiredPushChannel: {
        serializedName: "expiredPushChannel",
        readOnly: true,
        type: {
          name: "Boolean"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      templates: {
        serializedName: "templates",
        type: {
          name: "Dictionary",
          value: {
            type: { name: "Composite", className: "InstallationTemplateModel" }
          }
        }
      },
      secondaryTiles: {
        serializedName: "secondaryTiles",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "InstallationSecondaryTileModel"
            }
          }
        }
      }
    }
  }
};

export const InstallationTemplateModel: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "InstallationTemplateModel",
    modelProperties: {
      body: {
        serializedName: "body",
        required: true,
        type: {
          name: "String"
        }
      },
      headers: {
        serializedName: "headers",
        type: {
          name: "Dictionary",
          value: { type: { name: "String" } }
        }
      },
      expiry: {
        serializedName: "expiry",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const InstallationSecondaryTileModel: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "InstallationSecondaryTileModel",
    modelProperties: {
      pushChannel: {
        serializedName: "pushChannel",
        required: true,
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      templates: {
        serializedName: "templates",
        type: {
          name: "Dictionary",
          value: {
            type: { name: "Composite", className: "InstallationTemplateModel" }
          }
        }
      }
    }
  }
};

export const InstallationPatchModelItem: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "InstallationPatchModelItem",
    modelProperties: {
      op: {
        serializedName: "op",
        required: true,
        type: {
          name: "String"
        }
      },
      path: {
        serializedName: "path",
        required: true,
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const NotificationHubsClientGetInstallationHeaders: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "NotificationHubsClientGetInstallationHeaders",
    modelProperties: {
      contentLocation: {
        serializedName: "content-location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const NotificationHubsClientSendMessageHeaders: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "NotificationHubsClientSendMessageHeaders",
    modelProperties: {
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};
