/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  OperationParameter,
  OperationURLParameter,
  OperationQueryParameter
} from "@azure/core-client";

export const contentType: OperationParameter = {
  parameterPath: "contentType",
  mapper: {
    defaultValue: "application/octet-stream",
    isConstant: true,
    serializedName: "Content-Type",
    type: {
      name: "String"
    }
  }
};

export const body: OperationParameter = {
  parameterPath: "body",
  mapper: {
    serializedName: "body",
    required: true,
    type: {
      name: "Stream"
    }
  }
};

export const contentType1: OperationParameter = {
  parameterPath: "contentType",
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Content-Type",
    type: {
      name: "String"
    }
  }
};

export const body1: OperationParameter = {
  parameterPath: "body",
  mapper: {
    serializedName: "body",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const namespaceBaseUrl: OperationURLParameter = {
  parameterPath: "namespaceBaseUrl",
  mapper: {
    serializedName: "namespaceBaseUrl",
    required: true,
    type: {
      name: "String"
    }
  },
  skipEncoding: true
};

export const hubName: OperationURLParameter = {
  parameterPath: "hubName",
  mapper: {
    serializedName: "hubName",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const xMsVersion: OperationParameter = {
  parameterPath: "xMsVersion",
  mapper: {
    serializedName: "x-ms-version",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const authorization: OperationParameter = {
  parameterPath: "authorization",
  mapper: {
    serializedName: "Authorization",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const serviceBusNotificationDeviceHandle: OperationParameter = {
  parameterPath: "serviceBusNotificationDeviceHandle",
  mapper: {
    serializedName: "ServiceBusNotification-DeviceHandle",
    type: {
      name: "String"
    }
  }
};

export const serviceBusNotificationFormat: OperationParameter = {
  parameterPath: "serviceBusNotificationFormat",
  mapper: {
    serializedName: "ServiceBusNotification-Format",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const serviceBusNotificationTags: OperationParameter = {
  parameterPath: "serviceBusNotificationTags",
  mapper: {
    serializedName: "ServiceBusNotification-Tags",
    type: {
      name: "String"
    }
  }
};

export const apiVersion: OperationQueryParameter = {
  parameterPath: "apiVersion",
  mapper: {
    defaultValue: "2020-06-01",
    isConstant: true,
    serializedName: "api-version",
    type: {
      name: "String"
    }
  }
};

export const direct: OperationQueryParameter = {
  parameterPath: "direct",
  mapper: {
    serializedName: "direct",
    type: {
      name: "Boolean"
    }
  }
};
